/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package greeting;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.*;
import javax.swing.JFrame;
import java.awt.image.BufferedImage;
import java.io.File;
import java.awt.Image;
import javax.imageio.ImageIO;


/**
 *
 * @author MGP
 */
public class Frame extends javax.swing.JFrame {
   javax.swing.JFrame frame;
    /**
     * Creates new form Form
     */
    public Frame() {
        initComponents();
        setIcon();
        frame = this;
        frame.setResizable(false);
        frame.setTitle("Basic Greeting Program");
        ImageIcon icon = new ImageIcon("logo.png");
        frame.setIconImage(Toolkit.getDefaultToolkit().getImage("logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        greetBtn = new javax.swing.JButton();
        helloBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        defaultLabel = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Greeting Program");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        greetBtn.setBackground(new java.awt.Color(51, 51, 255));
        greetBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        greetBtn.setForeground(new java.awt.Color(255, 255, 255));
        greetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        greetBtn.setText("Greet");
        greetBtn.setBorderPainted(false);
        greetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greetBtnActionPerformed(evt);
            }
        });

        helloBtn.setBackground(new java.awt.Color(255, 102, 0));
        helloBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        helloBtn.setForeground(new java.awt.Color(255, 255, 255));
        helloBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chat.png"))); // NOI18N
        helloBtn.setText("Say Hello");
        helloBtn.setBorderPainted(false);
        helloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helloBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(helloBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(greetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 256, 680, 80);

        jPanel2.setBackground(new java.awt.Color(21, 24, 30));

        defaultLabel.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        defaultLabel.setForeground(new java.awt.Color(255, 255, 0));
        defaultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defaultLabel.setLabelFor(greetBtn);
        defaultLabel.setToolTipText("");
        defaultLabel.setFocusable(false);

        userInput.setBackground(new java.awt.Color(21, 24, 30));
        userInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userInput.setForeground(new java.awt.Color(131, 139, 157));
        userInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userInput.setToolTipText("Input your name ");
        userInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        userInput.setCaretColor(new java.awt.Color(255, 102, 51));
        userInput.setDisabledTextColor(new java.awt.Color(255, 102, 51));
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(defaultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(defaultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 680, 260);

        setBounds(0, 0, 693, 373);
    }// </editor-fold>//GEN-END:initComponents

    //add placeholder for user input 
    
    
    private void greetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greetBtnActionPerformed
        defaultLabel.setForeground(Color.green); 
        //clear output field
        if(!("".equals(defaultLabel.getText())))
            defaultLabel.setText("");
     
          String output = "Hey "; 
          
         //lengthen output area 
         
         
        if("".equals(userInput.getText())){
           //defaultLabel.setFont(new java.awt.Font("Sergio Print", java.awt.Font.BOLD,18));
           defaultLabel.setForeground(Color.red);
           defaultLabel.setText("type name first :(");
        }
        else {
            output += userInput.getText() + " :) "; 
            defaultLabel.setText(output); 
        }
    }//GEN-LAST:event_greetBtnActionPerformed

    private void helloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helloBtnActionPerformed
        defaultLabel.setForeground(Color.orange);  
        //clear output field
        if(!("".equals(defaultLabel.getText())))
            defaultLabel.setText("");
        //JOptionPane.showMessageDialog(rootPane, "Hello World!");
         defaultLabel.setText("Hello Human :)");
    }//GEN-LAST:event_helloBtnActionPerformed
    
    
    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
     /* @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defaultLabel;
    private javax.swing.JButton greetBtn;
    private javax.swing.JButton helloBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
